### ISSUE TITLE
go-cpe-dictionary not found 

### ISSUE THREAD

**Issue by 7h30th3r0n3** [vulsio/go-cpe-dictionary#37]
Hi ! thanks you for your work ! 

I got an issue after make install.

- Make install alone seem to dont work with this issue : 
go install -ldflags "-X 'github.com/kotakanbe/go-cpe-dictionary/config.Version=v0.2.6' -X 'github.com/kotakanbe/go-cpe-dictionary/config.Revision=a707cd1'"
go: cannot find GOROOT directory: /usr/local/go
make: *** [GNUmakefile:38 : install] Erreur 2

- So I sudo it :
sudo make install 

- And it work with this output :
go install -ldflags "-X 'github.com/kotakanbe/go-cpe-dictionary/config.Version=v0.2.6' -X 'github.com/kotakanbe/go-cpe-dictionary/config.Revision=a707cd1'"

- After this I try to fetch CPE data with command : 
gao-cpe-dictionary fetchnvd

- But I get : 

Command 'go-cpe-dictionary' not found, did you mean:
  command 'go-cve-dictionary' from deb go-cve-dictionary
Try: sudo apt install <deb name>

I dont know what happen ... 
it's the first time i use go ... 

thanks for your time / help

**Comment by kotakanbe** [comment]
Hi, @7h30th3r0n3 

Maybe you have an older version of GO.
Try the latest version.
https://golang.org/doc/install
